### ISSUE TITLE
Professor ratings not showing up

### ISSUE THREAD

**Issue by lufinkey** [isiah-lloyd/Katal#2]
I'm not seeing any professor ratings next to their name

![screenshot from 2018-01-10 10-15-18](https://user-images.githubusercontent.com/7820113/34779861-67dacb0a-f5ef-11e7-9ada-6e6f147abb5e.png)

**Comment by isiah-lloyd** [comment]
I beileve this is a problem with some professors at branch campsus. I will be looking into it.

**Comment by isiah-lloyd** [comment]
Has there been a search that worked for you? I did the same search as you and got successful results:

![image](https://user-images.githubusercontent.com/885544/34801655-d043c370-f637-11e7-8f3b-ff04cc5e1a41.png)

**Comment by lufinkey** [comment]
So far none of them have

**Comment by lufinkey** [comment]
Well it turns out all that was required was a simple restart of chrome after the plugin was installed. Not sure if that's a bug with chrome or your plugin though. There might be a method you can hook to start it after install?
